---
#<% require 'poise_boiler' %>
<%= PoiseBoiler.kitchen %>

chef_versions:
- '12.0'
- '12.1'
- '12.2'
- '12'

platforms:
- name: ubuntu-12.04

suites:
- name: default
  run_list:
  - recipe[poise_test]
  - recipe[poise_test::inversion]
