---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  network:
    - ["forwarded_port", {guest: 8080, host: 8080}]

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list:
  - recipe[apt]
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

suites:
- name: default
  run_list:
    - 'recipe[kibana]'
  attributes: {}
- name: kibana3
  run_list:
    - 'recipe[kibana]'
    - 'recipe[apache2]'
    - 'recipe[kibana::apache]'
  attributes:
    kibana:
      version: '3'
      nginx:
        listen_http: 8080
- name: kibana3_nginx
  run_list:
    - 'recipe[kibana]'
    - 'recipe[nginx]'
    - 'recipe[kibana::nginx]'
  attributes:
    kibana:
      version: '3'
- name: kibana3_source
  run_list:
    - 'recipe[kibana]'
    - 'recipe[apache2]'
    - 'recipe[kibana::apache]'
  attributes:
    kibana:
      version: '3'
      nginx:
        listen_http: 8080
      install_method: 'source'
- name: kibana4
  run_list:
    - 'recipe[kibana]'
  attributes:
    kibana:
      version: '4'
- name: kibana4_nginx
  run_list:
    - 'recipe[kibana]'
    - 'recipe[nginx]'
    - 'recipe[kibana::nginx]'
    - 'recipe[java]'
    - 'recipe[elasticsearch]'
  attributes:
    kibana:
      version: '4'
      nginx:
        listen_http: 8080
- name: kibana4_source
  run_list:
    - 'recipe[kibana]'
  attributes:
    kibana:
      version: '4'
      install_method: 'source'
